# Dependencies
markdown: redcarpet
hightlighter: pygments

# Permalinks
permalink: pretty

# Site settings
title: Marshall Bowers
tagline: ''
description: ''
username: maxdeviant
url: http://elliott.codes
paginate: 5