# Dependencies
markdown: redcarpet
hightlighter: pygments

# Permalinks
permalink: pretty

# Site settings
title: Marshall Bowers
tagline: ''
description: ''
url: http://elliott.codes

author:
  name: maxdeviant

paginate: 5