# Dependencies
markdown: redcarpet
hightlighter: pygments

# Permalinks
permalink: pretty

# Site settings
title: Marshall Bowers
tagline: Hacker
description: 'Marshall Bowers. Minimalist. Insatiable intellectual. Voracious programmer. Aspiring game developer.'
username: maxdeviant
url: http://elliott.codes
paginate: 5